### ISSUE TITLE
Supervising child processes in user context

### ISSUE THREAD

**Issue by zbalkan** [damianh/LittleForker#137]
Given that the supervision service is running under a high privilege account, e.g. SYSTEM, or local administrator, can we manage to fork/spawn/create child processes under user context with LittleForker for security reasons?

**Comment by damianh** [comment]
Honestly I have no idea as I have not tried / tested under such a scenario. If it does or does not work, please report back your findings :)

**Comment by zbalkan** [comment]
Well, I needed some pinvoke to get active user's access token and start the process with that. Then I monitor the process manually (loop + WMI query). I also need to ensure that the process instance is the one I managed, not a malicious faker. So I kill other processes, etc. I couldn't use LittleFork in that use case. Even if I try to use it, it will be heavily modified for a specific use case. I'll inform you if I do.

**Comment by damianh** [comment]
Thanks for info. I'll be assuming that LittleForker is only suitable for processes that run / spawn on the same account / user context.
