### ISSUE TITLE
The process loops in `Received command from server`

### ISSUE THREAD

**Issue by semion-akimtsev** [damianh/LittleForker#33]
Hi, looks like there is an issue with pipe reading and writing.

Steps:
Set the cooperative shutdown listening as
```
CooperativeShutdown.Listen(() => { });
```
Run the following script under elevated permissions:
```
gci \\.\pipe\
```
Observe the app enters a loop of messages: `Received command from server`

**Comment by damianh** [comment]
cc @osoykan
